services:
  bot:
    container_name: discord-sync-to-kook-bot
    build:
      context: .
      dockerfile: Dockerfile
    image: discord-sync-to-kook:local
    volumes:
      - ./.env:/app/.env
      - ./downloads:/app/downloads
      - ./data:/app/data
    command: ["python", "-m", "app.main"]
    restart: unless-stopped